In [1]:
import dask.dataframe as dd
from dask.distributed import Client

In [2]:
# Load the Parquet file
df = dd.read_parquet('data/processed/combined_parking_violations.parquet')

In [5]:
# Display the first few rows of the DataFrame
df.head()

,summons_number,plate_id,registration_state,plate_type,issue_date,violation_code,vehicle_body_type,vehicle_make,issuing_agency,street_code1,...,vehicle_color,unregistered_vehicle,vehicle_year,meter_number,feet_from_curb,violation_post_code,violation_description,no_standing_or_stopping_violation,hydrant_violation,double_parking_violation
0,1361929741,FCJ5493,NY,PAS,12/18/1970,20,SUBN,GMC,S,35030,...,BLACK,0,2013,-,0,<NA>,<NA>,<NA>,<NA>,<NA>
1,1366962000,63540MC,NY,COM,02/02/1971,46,DELV,FRUEH,P,58830,...,BRN,0,2013,-,0,<NA>,<NA>,<NA>,<NA>,<NA>
2,1342296187,GCY4187,NY,SRF,09/18/1971,21,VAN,FORD,S,11790,...,BLUE,0,2002,-,0,<NA>,<NA>,<NA>,<NA>,<NA>
3,1342296199,95V6675,TX,PAS,09/18/1971,21,<NA>,GMC,S,11790,...,SILVR,0,2008,-,0,<NA>,<NA>,<NA>,<NA>,<NA>
4,1342296217,FYM5117,NY,SRF,09/18/1971,21,SUBN,NISSA,S,28190,...,WHITE,0,2012,-,0,<NA>,<NA>,<NA>,<NA>,<NA>

In [6]:
# Compute the total number of rows in the DataFrame
# This operation will trigger a full computation
total_rows = df.shape[0].compute()
print("Total number of rows:", total_rows)

Total number of rows: 115023101.0

In [7]:
# Compute the total number of rows using a specific column, assuming 'summons_number' is always filled
total_rows = df['summons_number'].count().compute()
print("Total number of rows in summons_number column:", total_rows)

Total number of rows in summons_number column: 115023101

In [12]:
# Count of null values in 'summons_number' column
null_count = df['violation_description'].isnull().sum().compute()
print("Number of null values in violation_description column:", null_count)

# Count of non-null values in 'summons_number' column
non_null_count = df['violation_description'].notnull().sum().compute()
print("Number of non-null values in violation_description column:", non_null_count)

# Assuming empty strings and 'nonr' as specific cases to count, if necessary
empty_count = (df['violation_description'] == '').sum().compute()
nonr_count = (df['violation_description'] == 'nonr').sum().compute()

# Display results
print("Number of null values:", null_count)
print("Number of non-null values:", non_null_count)
print("Number of empty strings:", empty_count)
print("Number of 'nonr' values:", nonr_count)

Number of null values in violation_description column: 27866960
Number of non-null values in violation_description column: 87156141
Number of null values: 27866960
Number of non-null values: 87156141
Number of empty strings: 0
Number of 'nonr' values: 0